import express from "express";
import signupRouter from "./signupRouter.js";
import loginRouter from "./loginRouter.js";
import postRoutes from "./postRoutes.js";
import commentRoutes from "./commentRoutes.js";
const router = express.Router();
router.use('/auth', loginRouter); 
router.use('/posts', postRoutes); 
router.use('/auth', signupRouter); 
router.use("/comments", commentRoutes);
export default router;
